name: docs

on:
  # At 20:59 every tuesday (23:59 MSK)
  schedule:
    - cron: 59 20 * * 2

  # Manually triggerable in github
  workflow_dispatch:

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: codespell
      uses: codespell-project/actions-codespell@v2

  docs:
    runs-on: ubuntu-latest
    needs: codespell
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.7

      - name: installation pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.14.0.3/pandoc-2.14.0.3-1-amd64.deb
          sudo dpkg -i pandoc-2.14.0.3-1-amd64.deb

      - name: poetry install
        run: |
          poetry run python scripts/poetry_fix.py -c
          poetry install -E all

      - name: make documentations
        run: |
          cd docs
          poetry run make html
