name: tests_macos

on:
  # # At 20:59 every day (23:59 MSK)
  # schedule:
  #   - cron: 59 20 * * *

  # Manually triggerable in github
  workflow_dispatch:

  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  macos-tests:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python (Conda)
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true
          activate-environment: test

      - name: install deps for MacOS
        run: brew update && brew install libomp cairo pango gdk-pixbuf libffi

      - name: install conda dependencies
        run: |
          conda install numpy==1.26.4

      - name: install with pip
        run: |
          pip install tox==3.28.0
          pip install tox-gh-actions==2.12.0

      - name: test with tox
        run: |
          tox
